### use balance
POST http://localhost:8080/transaction/use
Content-Type: application/json

{
  "userId": 1,
  "accountNumber": "1000000000",
  "amount": 300000
}

### cancel balance
POST http://localhost:8080/transaction/cancel
Content-Type: application/json

{
  "transactionId": "e883828ef335461c80e53affe2391688",
  "accountNumber": "1000000000",
  "amount": 300000
}

### query transaction
GET http://localhost:8080/transaction/5c27741e786547068d6c2d23640782dd
